### ISSUE TITLE
ERROR LSP[tsserver] Inlay Hints request failed. File not opened in the editor.

### ISSUE THREAD

**Issue by aspeddro** [simrat39/inlay-hints.nvim#10]
Typescript LSP v3.0.0 dropped experimental inlay hints

https://github.com/typescript-language-server/typescript-language-server/pull/647

**Comment by moliva** [comment]
Hey, I just saw this issue. [I created this PR](https://github.com/simrat39/inlay-hints.nvim/pull/14) which adds a layer of configuration and uses the server capabilities to determine if the experimental or official support should be used.
