### ISSUE TITLE
trailing collons

### ISSUE THREAD

**Issue by caarlos0** [simrat39/inlay-hints.nvim#3]
<img width="909" alt="CleanShot 2022-11-25 at 00 03 03@2x" src="https://user-images.githubusercontent.com/245435/203892048-d21b70d0-600b-4d0b-a2dd-6c103338a74e.png">

in both go and lua I get those trailing collons... is it possible to get rid of them? 
I looked into the code, but didn't find where they come from... are them coming from the lsp server?

thanks for the great plugin, btw!

**Comment by benelan** [comment]
Yeah I'm pretty sure its coming from the lsp servers. I ended up using gsub to remove it, if you're still looking for a solution.

```lua
require("inlay-hints").setup {
  renderer = "inlay-hints/render/eol",
  eol = {
    parameter = {
      separator = ", ",
      format = function(hints)
        return string.format(" <- (%s)", hints):gsub(":", "")
      end,
    },
    type = {
      separator = ", ",
      format = function(hints)
        return string.format(" » (%s)", hints):gsub(":", "")
      end,
    },
  }
}

```

**Comment by caarlos0** [comment]
That does look a lot better, thank you!
